### ISSUE TITLE
Anonymous rating not possible

### ISSUE THREAD

**Issue by ihabunek** [joindin/joindin-web2#383]
Legacy web allows anon ratings, but web2 does not. Is this intentional?

Example:
https://joind.in/event/webcamp-zagreb-2016/the-code-manifesto-empowering-our-community
vs 
https://legacy.joind.in/talk/view/19116

**Comment by ihabunek** [comment]
This has not been fixed. Can you comment before closing please?

**Comment by liam-wiltshire** [comment]
Apologies @ihabunek  - we previously did not use github issues (issues should have been raised on JIRA) - I'm looking at moving issues into github (keeps everything in on place), but to start afresh I closed any old issues.

In short, it was intentional, however there are ongoing discussions internally about changing this -  see https://joindin.jira.com/browse/JOINDIN-756

**Comment by ihabunek** [comment]
Ok thanks. Will look into it on Jira. It's probably best to close issues on github when you're done moving them to avoid confusion.
