### ISSUE TITLE
Contact form doesn't work

### ISSUE THREAD

**Issue by eleftrik** [joindin/joindin-web2#432]
Today I tried to submit a request using your contact form. It doesn't work. I fill all fields, but when I submit it says "Failed:".
I was able to write only using the contact form on the legacy site.
Thank you

**Comment by wimhendrikx** [comment]
Same here! I think it is pretty important that your contact form works :-p

**Comment by mkopinsky** [comment]
Just as a datapoint, the contact form did *not* error in a local vagrant install. But I don't know if it's actually wired up to a mailer.

**Comment by railto** [comment]
Thank's for raising this, someone will look into it when they can.  As joind.in is an open source, contributor run platform it can take time for fixes to get implemented.  If you feel so inclined, you could always submit a pull request and we'd be more than delighted to take a look at it.

Thanks again.

**Comment by czmole** [comment]
I noticed that the master branch uses MailTransport but at the same time after dispatching the email, it return response 202 even if the email was not sent. 

If I output something on the method actually sending the email, it fails without a message, like it happened in the issue report.

I am thinking if in production it uses the same version of Swift mailer because I noticed the latest version MailTransport is deprecated (https://github.com/swiftmailer/swiftmailer/issues/866), in such case maybe it outputs some errors and the email is not sent.

**Comment by heiglandreas** [comment]
As sending the email might be an asyncronous task it's OK IMHO to send 202 no matter what the result of sending the email is.

Though as I noticed while moving everything to composer is that the current version of swiftmailer/swiftmailer is considered insecure by roave/security-advisories…

Perhaps we should change the underlying mailer-class? I'd vote for Zend\Mail but I'm sure there are others as well…

**Comment by mkopinsky** [comment]
There's no (security) need to switch away from swiftmailer, just upgrade to >5.4.5. Looks like currently `joindin-api` depends on `"swiftmailer/swiftmailer": "v5.0.3"` - changing that to `^5.0.3` (and then running `composer update` to update the lock file) will upgrade to 5.4.9 and resolve the security issue there.

**Comment by railto** [comment]
My vote is that we stick with swiftmailer, just update to something more current as @mkopinsky suggested

**Comment by heiglandreas** [comment]
Seems to work currently. At least there's no message "Failed" but a confirmation message
