### ISSUE TITLE
Feature request: account deletion

### ISSUE THREAD

**Issue by Mx-Glitter** [joindin/joindin-web2#438]
Hello,

I'd like to delete my JoindIn account, but I can't:

- I didn't find any account deletion feature
- I didn't find any contact information on the website

BTW, if someone here on the support side can help me, my account is Triiistan.

Thanks in advance! Sincerely.

**Comment by railto** [comment]
Hi @Mx-Glitter,

First off I'm sorry for the delay in getting back to you on this.

Account deletion is something that is manually processed, so that we can assist you with this, can you please send an email to info@joind.in from the email address on your joind.in profile so we can verify ownership.

Once you do this I'll take care of it for you.

Thanks again
